server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security?sessionVariables=sql_mode='NO_ENGINE_SUBSTITUTION'&jdbcCompliantTruncation=false
    username: root
    password: zaid@11
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

    database-platform: org.hibernate.dialect.MySQLDialect
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days



vonage:
  apiKey: afab8c03
  apiSecret: zQjyg80DAbcb2SfV




