server:
  port: 8084
  address: 192.168.1.102

spring:
  datasource:
    url: jdbc:mysql://neat-vent-389121:us-central1:mohamed2023/jabak_lah?useSSL=false
    username: root
    password: ENSA2023
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql

    database-platform: org.hibernate.dialect.MySQLDialect
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days



vonage:
  apiKey: 6077009c
  apiSecret: FiTPMyZGriGuCYN5




